version: "3.7"


services:
  nuxtjs:
    build: 
      context: "."
    image: nuxtjs:lat
    working_dir: /srv/app
    volumes: 
      - ".:/srv/app"
    ports:
      - "${EXPOSED_NODE_PORT:-80}:80"
